### ISSUE TITLE
Feedback/Questions about usage

### ISSUE THREAD

**Issue by josemarluedke** [rwjblue/sparkles-component#12]
I was playing out with sparkles components API and here a few questions/feedback. 

- Can a service be tracked? Or even, should it be?
- Constructor does not have access to container, so we can't use services inside of a component constructor. Is this the desired behavior or a bug?
- It seems that we can't have a tracked property on the component that depends on a property on a service. Bug? Or is the tracked and computed properties not playing with each other yet?
- Is the auto tracked feature not implemented in sparkles component, or is that the desired behavior?
- Since this is a new component API, could the property fallback behavior on templates (not using `this.`) be disabled in some way? (without relying template lint)
- Love the ability to type the args using generics.
- The Component API is awesome, simple and powerful.

Here is a repo where I was playing with: https://github.com/josemarluedke/--sparkles-test

**Comment by rwjblue** [comment]
> Can a service be tracked? Or even, should it be?

Services are singletons and therefore can’t change. I wouldn’t really expect a service to be tracked. 

> Constructor does not have access to container, so we can't use services inside of a component constructor. Is this the desired behavior or a bug?

This is somewhat intentional, but mostly because I don’t have a motivating example where you would need it in constructor. Feel free to open a specific issue to discuss a path forward here...

> It seems that we can't have a tracked property on the component that depends on a property on a service. Bug? Or is the tracked and computed properties not playing with each other yet?

Well, you can’t track “paths” in the current implementation (which is what you are pointing out). I think I would use a decorator (from `ember-decorators`) to make this nice. 

> Is the auto tracked feature not implemented in sparkles component, or is that the desired behavior?

Auto track requires support by Ember, and I couldn’t figure out how to polyfill in a public API way. I definitely think auto track is going to be preferable. 

> Since this is a new component API, could the property fallback behavior on templates (not using this.) be disabled in some way? (without relying template lint)

I did think about this during initial implementation, but couldn’t figure out how to do it at a per-manager level. I think we would need a new capability in the component manager API to allow opting out.

**Comment by josemarluedke** [comment]
Thanks for the answers, I really appreciate it. 

>  think I would use a decorator (from ember-decorators) to make this nice.

Are you referring to the `@computed` decorators in this case? 

If (when) `@tracked` is enabled in Ember, are we going to need to need to use `@tracked` and `@computed` at the same time? For this sort of cases?

**Comment by josemarluedke** [comment]
Closing this as I believe I got all my questions answered in one way or the other. Thanks.
