### ISSUE TITLE
blueprint generates incorrect class names for nested components?

### ISSUE THREAD

**Issue by lougreenwood** [rwjblue/sparkles-component#24]
If I use the blueprint to generate a nested component (in this case for a contextual component), it seems that an invalid class name is generated:

**generate:**
```
ember g sparkles-component button-group/button
```

**result:**
```
import Component from 'sparkles-component';

export default class ButtonGroup/button extends Component {

}
```

The class name `ButtonGroup/button` seems to be invalid and results in the following error being thrown when building:

```
components/button-group/button.js: Unexpected token, expected "{" (3:32)

  1 | import Component from 'sparkles-component';
  2 |
> 3 | export default class ButtonGroup/button extends Component {
    |                                 ^
  4 |
  5 | }
  6 |
```

**Comment by mike-north** [comment]
oops! I think the blueprint I based this on has the same problem. This is a legit bug

**Comment by buschtoens** [comment]
Shouldn't we be able to just remove `classifiedModuleName` from the `locals`, since it is provided by the [`Blueprint` base class](https://github.com/ember-cli/ember-cli/blob/5ed36452b3d938935a69d47cfbd4228374cdc8ba/lib/models/blueprint.js#L833-L864) already?

https://github.com/rwjblue/sparkles-component/blob/e320c6ffba4681fe3cbcb74abcbe24aad7bffef7/blueprints/sparkles-component/index.js#L101-L109

If this was added for backwards compatibility with older ember-cli versions, we could just do it like it's done in `Blueprint`.

**Comment by rwjblue** [comment]
See https://github.com/rwjblue/sparkles-component/pull/33, closing in favor of using `@glimmer/component` directly.
